Annotation:
  test: 'Working!'
Title:
  test:
    title: '&bHello!'
    sub-title: '&fThis is a test title!'
    fade-in: 20
    stay: 40
    fade-out: 20
Enum:
  test: 'HEAD'
# This is a test comment!
TestValue: 'Hello World'
Settings:
  disable-notification-on-join: false # Should we disable the notification on join?. Keep in mind that notification is only available for player who have oreocore.admin permission