name: OreoCore
version: 4.2
main: me.droreo002.oreocore.OreoCore
depend: [ProtocolLib]
softdepend: [Essentials]
api-version: 1.13

commands:
  customcommand:
    aliases:
      - customcmd
  oreocore:
    aliases:
      - ocore
      - orcore
