name: OreoCore
version: 1.10
main: me.droreo002.oreocore.OreoCore
depend: [ProtocolLib]
softdepend: [Essentials]

commands:
  customcommand:
    aliases:
      - customcmd
  oreocore:
    aliases:
      - ocore
      - orcore
